import { resolve } from "node:path";
import type {
  LanguageModelV3Content,
  LanguageModelV3Message,
  LanguageModelV3TextPart,
  SharedV3ProviderOptions,
} from "@ai-sdk/provider";
import type { ContextAssembledSource, SkillsLoadedEntry } from "../engine/types.ts";
import type { TokenUsage } from "../usage/types.ts";

// Re-export so conversation-event consumers don't need to know these
// originate in engine/types.ts. Engine emits them; conversation persists
// them; one definition keeps the wire shape from drifting.
export type { ContextAssembledSource, SkillsLoadedEntry };

/**
 * Conversation IDs are `conv_` followed by exactly 16 lowercase hex characters.
 * Generated by: `conv_${crypto.randomUUID().replace(/-/g, "").slice(0, 16)}`
 */
export const CONVERSATION_ID_RE = /^conv_[a-f0-9]{16}$/;

/**
 * Validate a conversation ID and resolve its file path safely.
 * Throws if the ID format is invalid or the resolved path escapes the base directory.
 */
export function validateConversationId(id: string, dir: string): void {
  if (!CONVERSATION_ID_RE.test(id)) {
    throw new Error(`Invalid conversation ID: must match conv_ + 16 hex chars`);
  }
  const resolved = resolve(dir, `${id}.jsonl`);
  if (!resolved.startsWith(resolve(dir))) {
    throw new Error("Path traversal detected");
  }
}

/** Access context for filtering conversations by user identity and role. */
export interface ConversationAccessContext {
  userId: string;
  workspaceRole?: "admin" | "member";
}

/** Options for listing conversations. */
export interface ListOptions {
  limit?: number;
  cursor?: string;
  search?: string;
  sortBy?: "createdAt" | "updatedAt";
}

/** Paginated conversation list result. */
export interface ConversationListResult {
  conversations: ConversationSummary[];
  nextCursor: string | null;
  totalCount: number;
}

/** Options for creating a new conversation. */
export interface CreateConversationOptions {
  workspaceId?: string;
  ownerId?: string;
  visibility?: "private" | "shared";
  participants?: string[];
  metadata?: Record<string, unknown>;
}

/** Fields that can be updated on a conversation. */
export interface ConversationPatch {
  title?: string;
}

export interface ConversationSummary {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string | null;
  messageCount: number;
  preview: string;
  totalInputTokens: number;
  totalOutputTokens: number;
  totalCostUsd: number;
  ownerId?: string;
  visibility?: "private" | "shared";
  workspaceId?: string;
  participants?: string[];
}

export interface ConversationStore {
  create(options?: CreateConversationOptions): Promise<Conversation>;
  load(id: string, access?: ConversationAccessContext): Promise<Conversation | null>;
  append(conversation: Conversation, message: StoredMessage): Promise<void>;
  history(conversation: Conversation, limit?: number): Promise<StoredMessage[]>;
  list(options?: ListOptions, access?: ConversationAccessContext): Promise<ConversationListResult>;
  /** Delete a conversation and its backing store. Returns true if found. */
  delete(id: string): Promise<boolean>;
  /** Update conversation metadata. Returns updated conversation or null if not found. */
  update(id: string, patch: ConversationPatch): Promise<Conversation | null>;
  /** Fork a conversation, optionally truncating at a specific message index. */
  fork(id: string, atMessage?: number): Promise<Conversation | null>;
  /** Change visibility from private to shared. Only the owner (or admin) may call this. */
  shareConversation(id: string, ownerId: string): Promise<Conversation | null>;
  /** Change visibility back to private. Removes all participants except the owner. */
  unshareConversation(id: string, ownerId: string): Promise<Conversation | null>;
  /** Add a participant to a shared conversation. */
  addParticipant(id: string, userId: string): Promise<Conversation | null>;
  /** Remove a participant from a shared conversation. Cannot remove the owner. */
  removeParticipant(id: string, userId: string): Promise<Conversation | null>;
}

/**
 * Conversation metadata — stored as line 1 of the JSONL file.
 *
 * No token totals or cost — those are derived from events at read time
 * (see deriveUsageMetrics in event-reconstructor.ts and the index cache).
 * Storing them invited drift bugs where the cached total didn't match
 * what re-aggregating the events would produce.
 */
export interface Conversation {
  id: string;
  createdAt: string;
  updatedAt: string;
  title: string | null;
  lastModel: string | null;
  /** Workspace this conversation belongs to. */
  workspaceId?: string;
  /** User who created this conversation. */
  ownerId?: string;
  /** Visibility: private (default) or shared within workspace. */
  visibility?: "private" | "shared";
  /** User IDs participating in this conversation. */
  participants?: string[];
  /** Arbitrary caller-provided metadata. Stored in JSONL first line, never validated. */
  metadata?: Record<string, unknown>;
  /** File format discriminator. "events" for event-sourced files. Absent for legacy message format. */
  format?: "events";
}

/** Participant info for system prompt injection in shared conversations. */
export interface ParticipantInfo {
  userId: string;
  displayName?: string;
}

/**
 * MCP `resource_link` content block — references a workspace resource
 * (typically `files://<id>`) by URI. The bytes live in the resource's
 * owning store; the conversation log carries only the link.
 *
 * The runtime rehydrates image links to AI SDK V3 `file` parts at the
 * `model.doStream` boundary so vision content reaches the model without
 * the JSONL ever holding raw bytes.
 */
export interface ResourceLinkContentPart {
  type: "resource_link";
  uri: string;
  mimeType: string;
  name: string;
}

/**
 * User-message content shape — text plus MCP `resource_link` blocks.
 * Narrower than `LanguageModelV3UserMessage["content"]` (which also
 * permits inline file parts): callers persist references, not bytes.
 */
export type UserContentPart = LanguageModelV3TextPart | ResourceLinkContentPart;

interface StoredMessageMetadata {
  skill?: string | null;
  toolCalls?: Array<{
    id: string;
    name: string;
    input: Record<string, unknown>;
    output: string;
    ok: boolean;
    ms: number;
    resourceUri?: string;
    resourceLinks?: Array<{
      uri: string;
      name?: string;
      mimeType?: string;
      description?: string;
    }>;
  }>;
  /** Cumulative usage for the assistant turn. Cost is derived at read time. */
  usage?: TokenUsage;
  model?: string;
  llmMs?: number;
  iterations?: number;
  /** Per-call finish reason — surfaces length truncation etc. to the UI. */
  finishReason?: "stop" | "length" | "content-filter" | "tool-calls" | "error" | "other";
  files?: Array<{
    id: string;
    filename: string;
    mimeType: string;
    size: number;
    extracted: boolean;
  }>;
}

interface StoredMessageExtras {
  timestamp: string;
  /** User who sent this message (for multi-user conversations). */
  userId?: string;
  metadata?: StoredMessageMetadata;
}

/**
 * In-memory message shape used by the runtime and event store.
 *
 * For non-user roles, this is `LanguageModelV3Message` plus the platform's
 * timestamp/metadata extras. For user role we widen the content union to
 * include `resource_link` blocks so attached images survive end-to-end as
 * URI references; the runtime rehydrates them to AI SDK `file` parts before
 * calling the model.
 */
export type StoredMessage = StoredMessageExtras &
  (
    | { role: "user"; content: UserContentPart[]; providerOptions?: SharedV3ProviderOptions }
    | Exclude<LanguageModelV3Message, { role: "user" }>
  );

// ---------------------------------------------------------------------------
// Event-sourced conversation events
// ---------------------------------------------------------------------------

export type ConversationEventType =
  | "user.message"
  | "run.start"
  | "llm.response"
  | "tool.start"
  | "tool.done"
  | "tool.progress"
  | "run.done"
  | "run.error"
  | "skills.loaded"
  | "context.assembled"
  | "metadata.title"
  | "metadata.visibility"
  | "metadata.participants";

export interface UserMessageEvent {
  ts: string;
  type: "user.message";
  /**
   * Persisted content. Text + MCP `resource_link` blocks only — never
   * inline bytes. See `UserContentPart`.
   */
  content: UserContentPart[];
  userId?: string;
  files?: Array<{
    id: string;
    filename: string;
    mimeType: string;
    size: number;
    extracted: boolean;
  }>;
}

export interface RunStartEvent {
  ts: string;
  type: "run.start";
  runId: string;
  model: string;
  /** Present only when logging.level is "debug". */
  systemPrompt?: string;
  /** Present only when logging.level is "debug". */
  messages?: unknown[];
  /** Present only when logging.level is "debug". */
  toolSchemas?: string[];
}

export interface LlmResponseEvent {
  ts: string;
  type: "llm.response";
  runId: string;
  model: string;
  /**
   * V3 content blocks. Includes `text`, `tool-call`, and `reasoning`
   * (extended thinking) parts. Reasoning blocks are surfaced to the UI
   * collapsed-by-default; bare absence on a turn with non-stop
   * finishReason is what indicates a real empty turn.
   */
  content: LanguageModelV3Content[];
  /** Token usage for this single LLM call (canonical AI SDK V3 shape). */
  usage: TokenUsage;
  llmMs: number;
  /**
   * Per-call finish reason from the provider (AI SDK V3 unified value).
   * Optional for backward-compat with conversations recorded before this
   * field existed.
   */
  finishReason?: "stop" | "length" | "content-filter" | "tool-calls" | "error" | "other";
}

export interface ToolStartEvent {
  ts: string;
  type: "tool.start";
  runId: string;
  name: string;
  id: string;
  /** Present only when logging.level is "debug". */
  input?: unknown;
}

export interface ToolDoneEvent {
  ts: string;
  type: "tool.done";
  runId: string;
  name: string;
  id: string;
  ok: boolean;
  ms: number;
  /** Present only when logging.level is "debug". */
  output?: string;
}

export interface ToolProgressEvent {
  ts: string;
  type: "tool.progress";
  runId: string;
  id: string;
  message: string;
}

export interface RunDoneEvent {
  ts: string;
  type: "run.done";
  runId: string;
  stopReason: string;
  totalMs: number;
}

export interface RunErrorEvent {
  ts: string;
  type: "run.error";
  runId: string;
  error: string;
  errorType: string;
}

export interface TitleChangeEvent {
  ts: string;
  type: "metadata.title";
  title: string | null;
}

export interface VisibilityChangeEvent {
  ts: string;
  type: "metadata.visibility";
  visibility: "private" | "shared";
}

export interface ParticipantsChangeEvent {
  ts: string;
  type: "metadata.participants";
  participants: string[];
}

export interface SkillsLoadedEvent {
  ts: string;
  type: "skills.loaded";
  runId: string;
  skills: SkillsLoadedEntry[];
  totalTokens: number;
}

export interface ContextAssembledEvent {
  ts: string;
  type: "context.assembled";
  runId: string;
  sources: ContextAssembledSource[];
  excluded: ContextAssembledSource[];
  totalTokens: number;
  modelMaxContext?: number;
  headroomTokens?: number;
}

/** Discriminated union of all conversation event types. */
export type ConversationEvent =
  | UserMessageEvent
  | RunStartEvent
  | LlmResponseEvent
  | ToolStartEvent
  | ToolDoneEvent
  | ToolProgressEvent
  | RunDoneEvent
  | RunErrorEvent
  | SkillsLoadedEvent
  | ContextAssembledEvent
  | TitleChangeEvent
  | VisibilityChangeEvent
  | ParticipantsChangeEvent;
