/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/tools/platform/schemas/manage-tools.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
import { type Static } from "@sinclair/typebox";
export declare const ManageToolsInput: import("@sinclair/typebox").TObject<{
    add: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
    remove: import("@sinclair/typebox").TOptional<import("@sinclair/typebox").TArray<import("@sinclair/typebox").TString>>;
}>;
export type ManageToolsInput = Static<typeof ManageToolsInput>;
