#!/usr/bin/env bun
/**
 * Generates `web/src/_generated/platform-schemas/` from the canonical
 * TypeBox schemas at `src/tools/platform/schemas/`.
 *
 * Why this exists: web is a separate package (its own Dockerfile,
 * package.json, build context). The web shell needs the catalog's
 * derived TYPES — `ToolInput<S, T>`, `ToolSource`, `ToolName<S>` — for
 * the typed `callTool<S, T>(args)` API in `web/src/api/client.ts` and
 * the `CreateInput` alias in `web/src/pages/settings/SkillsTab.tsx`.
 * It does NOT need the runtime schemas (TypeBox values).
 *
 * Sharing this via a cross-tree TypeScript path alias would force every
 * Dockerfile, dockerignore, Makefile, docker-compose, and CI invocation
 * to know about the cross-tree relationship. Generating a flat .d.ts
 * tree inside web/ keeps web a self-contained package — its build
 * doesn't reach outside web/, and the generated artifact is a normal
 * source file in version control.
 *
 * The generated tree is checked in. CI runs this script and verifies
 * `git diff --exit-code web/src/_generated/` to catch drift.
 *
 * Run: `bun run codegen` (alias for this script — see package.json).
 */

import { execSync } from "node:child_process";
import { cpSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dirname ?? __dirname, "..");
const SCHEMA_SRC = join(REPO_ROOT, "src/tools/platform/schemas");
const TMP_OUT = join(REPO_ROOT, ".tmp-codegen");
const WEB_DEST = join(REPO_ROOT, "web/src/_generated/platform-schemas");
const WORKSPACE_ID_PATTERN_SRC = join(REPO_ROOT, "src/workspace/workspace-id-pattern.ts");
const WORKSPACE_ID_PATTERN_DEST = join(REPO_ROOT, "web/src/_generated/workspace-id-pattern.ts");

/**
 * Per-file header injected at the top of every generated .d.ts.
 * No timestamp — would change every regen and defeat the CI drift
 * check (`git log <file>` is the authoritative regen record).
 */
function header(sourcePath: string): string {
  return `/**
 * AUTOGENERATED — DO NOT EDIT. Source: ${sourcePath}
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */
`;
}

/** Recursively prepend the header to every .d.ts file in `dir`. */
function injectHeaders(dir: string, sourceRoot: string): void {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      injectHeaders(full, sourceRoot);
      continue;
    }
    if (!entry.name.endsWith(".d.ts")) continue;
    // Map output path back to source path for the header.
    const relFromOutput = full.slice(WEB_DEST.length + 1).replace(/\.d\.ts$/, ".ts");
    const sourcePath = `src/tools/platform/schemas/${relFromOutput}`;
    const body = readFileSync(full, "utf-8");
    writeFileSync(full, header(sourcePath) + body);
  }
}

// ── workspace-id-pattern (Stage 2 / T012) ──────────────────────────
//
// Emits a runtime `.ts` mirroring the literal pattern + flags exported
// from `src/workspace/workspace-id-pattern.ts`. The web tier
// (`web/src/lib/namespaced-tool.ts`) imports the generated copy and
// constructs its own RegExp locally. CI's `check:codegen` step
// (`git diff --exit-code web/src/_generated/`) catches drift between
// the server source and the emitted copy.
//
// Why we don't ship a `.d.ts` here: the web tier needs the actual
// string values at runtime to validate workspace ids. `.d.ts` would
// only give us type-level types. So this step is a hand-written extract
// of the two string literals — no `tsc` emission needed.

function extractStringLiteral(source: string, name: string): string {
  // Match `export const <name> = "<value>";` with the value as a
  // double-quoted JS string literal. No escapes are interpreted — the
  // workspace-id pattern uses only ASCII + the chars `^$_{},|[]0-9a-z`,
  // none of which need escaping in a JS string. If a future change to
  // the source adds escapes, this regex needs to widen accordingly.
  const re = new RegExp(`export\\s+const\\s+${name}\\s*=\\s*"([^"\\\\]*)"`);
  const m = re.exec(source);
  if (!m || typeof m[1] !== "string") {
    throw new Error(
      `[codegen] could not extract ${name} from ${WORKSPACE_ID_PATTERN_SRC} — the source file format may have changed`,
    );
  }
  return m[1];
}

console.log("[codegen] workspace-id-pattern → web/src/_generated/workspace-id-pattern.ts");

{
  const src = readFileSync(WORKSPACE_ID_PATTERN_SRC, "utf-8");
  const pattern = extractStringLiteral(src, "WORKSPACE_ID_PATTERN");
  const flags = extractStringLiteral(src, "WORKSPACE_ID_FLAGS");

  // JSON.stringify produces a safely-quoted JS string literal even if
  // someone slips a `"` or `\` into the pattern later. Defense in depth
  // against silent codegen breakage.
  const patternLiteral = JSON.stringify(pattern);
  const flagsLiteral = JSON.stringify(flags);

  const body = `${header("src/workspace/workspace-id-pattern.ts")}
// Workspace-id pattern + flags mirrored from the server-side source.
// The web tier rebuilds the regex locally; see the source file's
// header for the contract.

export const WORKSPACE_ID_PATTERN = ${patternLiteral};
export const WORKSPACE_ID_FLAGS = ${flagsLiteral};
`;

  mkdirSync(dirname(WORKSPACE_ID_PATTERN_DEST), { recursive: true });
  writeFileSync(WORKSPACE_ID_PATTERN_DEST, body);
  console.log(`[codegen] OK → ${WORKSPACE_ID_PATTERN_DEST.replace(REPO_ROOT, ".")}`);
}

console.log("[codegen] platform-schemas → web/src/_generated/platform-schemas/");

// Clean previous outputs so removed schemas don't leave stale .d.ts files.
rmSync(TMP_OUT, { recursive: true, force: true });
rmSync(WEB_DEST, { recursive: true, force: true });

// Emit declarations only via the dedicated tsconfig. The dedicated config
// keeps the generation independent of the project tsconfig (which uses
// `noEmit` and other compile-time-only settings).
execSync(`bunx tsc -p scripts/tsconfig.codegen-web.json`, {
  cwd: REPO_ROOT,
  stdio: "inherit",
});

// The tsc output preserves the source dir structure under `outDir`.
// Move just the schemas tree into web/src/_generated/.
mkdirSync(dirname(WEB_DEST), { recursive: true });
cpSync(TMP_OUT, WEB_DEST, { recursive: true });
rmSync(TMP_OUT, { recursive: true, force: true });

// Inject the do-not-edit header into every generated file.
injectHeaders(WEB_DEST, SCHEMA_SRC);

console.log(`[codegen] OK → ${WEB_DEST.replace(REPO_ROOT, ".")}`);
