/**
 * AUTOGENERATED — DO NOT EDIT. Source: src/workspace/workspace-id-pattern.ts
 * Regenerate: bun run codegen. AI agents: edit the source, not this file.
 */

// Workspace-id pattern + flags mirrored from the server-side source.
// The web tier rebuilds the regex locally; see the source file's
// header for the contract.

export const WORKSPACE_ID_PATTERN = "^ws_[a-z0-9_]{1,64}$";
export const WORKSPACE_ID_FLAGS = "i";
